name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Generate NuGet package
      run: dotnet pack -c Release -o . --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)

    - name: Push to GitHub package registry
      run: dotnet nuget push *.nupkg -s https://nuget.pkg.github.com/crafters-cloud/index.json --skip-duplicate
